// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Programa2_TP3CSharp_ASP.NET.Data;

#nullable disable

namespace Programa2_TP3CSharp_ASP.NET.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240907212552_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Programa2_TP3CShpar_ASP.NET.Models.Passaporte", b =>
                {
                    b.Property<int>("PassaportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaisDeOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassaportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PassaportId");

                    b.ToTable("Passaportes");
                });

            modelBuilder.Entity("Programa2_TP3CShpar_ASP.NET.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Programa2_TP3CShpar_ASP.NET.Models.Passaporte", b =>
                {
                    b.HasOne("Programa2_TP3CShpar_ASP.NET.Models.Pessoa", "Pessoa")
                        .WithOne("Passaporte")
                        .HasForeignKey("Programa2_TP3CShpar_ASP.NET.Models.Passaporte", "PassaportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Programa2_TP3CShpar_ASP.NET.Models.Pessoa", b =>
                {
                    b.Navigation("Passaporte")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
